### ISSUE TITLE
Critical Error Upon Setup

### ISSUE THREAD

**Issue by rogueatom** [YahnisElsts/wp-update-server#101]
I have added the server setup code and used the test url to verify the .json plugin package system works.

Loads fine, shows the data for the plugin.

I then added the block of code to my plugin for the Update Checker and uploaded to the site.

Last I added the block specified on the Update Server instructions to point to the folder for the Update Checker and the Update Server for the json details.

When I update the plugin with that code I get the WP "Critical Error" page and it all fails.

I checked the files were all uploaded and confirmed things were named properly. So I am not sure what to do from here.

**Comment by rogueatom** [comment]
Ok, I will see what the logs show.

My thought was maybe the "Add this code" to the plugin part I was not updating all the bits properly or something else got missed in the jumping around.

**Comment by rogueatom** [comment]
I was able to get this issue resolved, was a path error due to server setup.

**Comment by YahnisElsts** [comment]
All right, I'll close this issue then.
