### ISSUE TITLE
How about implementing WordPress Code Standards?

### ISSUE THREAD

**Issue by ddur** [YahnisElsts/wp-update-server#107]
Running PHPCS with WPCS over code warns about code (or security) practices and of course makes repository compliant with WordPress coding rules/standards. 

It is not that I especially like rules :grin: , but in addition to complying to standard they make code searching easier.

**Comment by YahnisElsts** [comment]
I had already done some WPCS compliance stuff since I use PUC in a plugin that uses PHPCS/WPCS. Now I've added a `phpcs.xml` configuration file for PUC specifically, and I've fixed or silenced all current warnings and errors.

**Comment by ddur** [comment]
> _Edit:_ Oops, I was looking at the wrong repository. Disregard this comment. PHPCS has _not_ been implemented yet.

Hi Yahnis. 

Would you accept PR with your PHP code reformatted to comply with WordPress Coding Standards?

**Comment by YahnisElsts** [comment]
No need, I went through the PHPCS reports for _this_ repository now, and fixed/silenced most things.

There are still warnings/errors in the external dependencies (excluded via `phpcs.xml`), but I'm not sure it's worth fixing those. You would probably have to rewrite the metadata parser entirely to make it compliant.

**Comment by ddur** [comment]
Thanks
