### ISSUE TITLE
PHP 8.2.7 Deprecated warnings on Server returning metadata (WP_DEBUG true)

### ISSUE THREAD

**Issue by ddur** [YahnisElsts/wp-update-server#109]
<br />
<b>Deprecated</b>:  Return type of Wpup_Headers::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/home/test/public_html/wp-content/plugins/warp-updates/classes/wp-update-server-2.0/includes/Wpup/Headers.php</b> on line <b>129</b><br />
<br />
<b>Deprecated</b>:  Return type of Wpup_Headers::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/home/test/public_html/wp-content/plugins/warp-updates/classes/wp-update-server-2.0/includes/Wpup/Headers.php</b> on line <b>133</b><br />
<br />
<b>Deprecated</b>:  Return type of Wpup_Headers::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/home/test/public_html/wp-content/plugins/warp-updates/classes/wp-update-server-2.0/includes/Wpup/Headers.php</b> on line <b>137</b><br />
<br />
<b>Deprecated</b>:  Return type of Wpup_Headers::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/home/test/public_html/wp-content/plugins/warp-updates/classes/wp-update-server-2.0/includes/Wpup/Headers.php</b> on line <b>141</b><br />
<br />
<b>Deprecated</b>:  Return type of Wpup_Headers::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/home/test/public_html/wp-content/plugins/warp-updates/classes/wp-update-server-2.0/includes/Wpup/Headers.php</b> on line <b>154</b><br />
<br />
<b>Deprecated</b>:  Return type of Wpup_Headers::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/home/test/public_html/wp-content/plugins/warp-updates/classes/wp-update-server-2.0/includes/Wpup/Headers.php</b> on line <b>148</b><br />

**Comment by YahnisElsts** [comment]
Hmm, I thought this was already fixed in 2.0.1. Can you test with that version?

**Comment by ddur** [comment]
Yes indeed, I'm using 2.0 version since January.
I will check again and let you know.

**Comment by ddur** [comment]
@YahnisElsts 

No warnings in 2.0.1

Thanks
