### ISSUE TITLE
What's going on here?

### ISSUE THREAD

**Issue by ddur** [YahnisElsts/wp-update-server#113]
https://github.com/YahnisElsts/wp-update-server/pull/112

**Comment by YahnisElsts** [comment]
Who knows. Maybe someone had a fork for their own use, and they created a PR by mistake. I'm certainly not planning to merge it.

**Comment by martynasumb** [comment]
> 

That's what happened, you can delete this PR. I apologize.

**Comment by YahnisElsts** [comment]
No problem. I don't see an option to completely delete it, but I think it's fine to leave it. I'll just tag it as invalid.
