### ISSUE TITLE
Extensibility of Header Parser in wp-update-server

### ISSUE THREAD

**Issue by 3ele-projects** [YahnisElsts/wp-update-server#127]
Hello @YahnisElsts,

I'm currently using your `wp-update-server` project in one of my applications and it works fantastically. Thank you for your efforts in maintaining this project.

 Recently, I've encountered a requirement where I need to augment the functionality of the Header Parser. Upon delving through the code and documentation, it appears that its design doesn't seem to support inheritance, thereby limiting the extendibility maneuverability of the component.
 
 Could you assist by providing some advice or reference points on how to best perform this extension? Any guidance herein would be immensely advantageous and appreciated.
 
My first steps would be a fork for the introduction of namespaces (e.g. for psr-4 autoloading) 

Is there anything against it, or would you be interested in introducing namespaces? 

Best Regards

**Comment by YahnisElsts** [comment]
If you're going to make a fork, the most obvious place to add new headers is probably the [getPluginHeaders()](https://github.com/YahnisElsts/wp-update-server/blob/74fe540e2a70cfc559376bd83a7f4447ffa998d9/includes/extension-meta/extension-meta.php#L253) method. Or, if you want to change the actual parsing of headers, consider the [getFileHeaders()](https://github.com/YahnisElsts/wp-update-server/blob/74fe540e2a70cfc559376bd83a7f4447ffa998d9/includes/extension-meta/extension-meta.php#L364) method.

In principle, I have nothing against introducing namespaces. Parts of this code are just very old - written before WordPress required a PHP version supporting namespaces. However, I'm not currently actively developing this project, just maintaining it. So it's not likely that I'll make sweeping changes like converting everything to use namespaces.

**Comment by 3ele-projects** [comment]
Thanks for your answer.

I imported your package into a Symfony project via composer, where I then noticed it, or rather fell on my feet (the missing namespaces). This means that the Composer package is only partially usable (correct me if I'm wrong)

I would like to tackle this potentially or do you think that the effort is not worth it or do you see downward compatible problems?

Would you accept an MR, or what would be the basis for it?
