### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by Streamlinelv** [YahnisElsts/wp-update-server#129]
Hi, could you please include some changelog or version number along with the code?
At this point it does not seem to be possible to tell what version we are currently using and if it is the latest one or not.

Thank you

**Comment by YahnisElsts** [comment]
All right, I've added it here: [`includes/Version.php`](https://github.com/YahnisElsts/wp-update-server/blob/444ab4b981c55aad92bf34f669b84095725eeb11/includes/Version.php#L3)

I didn't find a convenient way to fully automate updating the code, so I'll have to remember to edit the file before each release.

**Comment by Streamlinelv** [comment]
Thank you!
