### ISSUE TITLE
Swtiching from Apache to Nginx server

### ISSUE THREAD

**Issue by Streamlinelv** [YahnisElsts/wp-update-server#130]
Hi Janis,
I have switched over from Apache to Nginx server and I'm tryning to protect the wp-update server folders.
Since .htaccess files do not work on Nginx, I'm struggling to come up with a solution to protect the logs and packages folders.

I tried adding the code below into Nginx cinfiguration, but I'm still able to directly access package .zip file.

 location /wp-content/wp-update-server/packages/ {
      deny all;
      return 403;
 }

**Comment by YahnisElsts** [comment]
I don't really have any experience with Nginx myself, so, unfortunately, I don't think I can offer any useful advice here.

**Comment by Streamlinelv** [comment]
Thank you for your fast response!

**Comment by SGr33n** [comment]
The code is correct, is it possible that you inserted in the wrong place?
Probably you have a main /etc/nginx/nginx.conf and then the vhost file inside /etc/nginx/sites-available/, here you have to insert the code, inside server {}

```
server {

    [ ... ]

    location /wp-content/wp-update-server/packages/ {
        deny all;
        return 403;
    }
}
```

Then you have to reload nginx.

`service nginx reload`

**Comment by Streamlinelv** [comment]
Thank you for assistance Sergio,
The code that I posted before was saved in CloudPanel Vhost file in between the server{}, but it did not have any effect. I might look for the other file you mentioned and try adding it there.

**Comment by Streamlinelv** [comment]
Turns out Vhost was the correct place, however the rule had to look a bit different:

  location ~* /wp-content/wp-update-server/packages/ {
    if ( $upstream_http_x_accel_redirect = "" ) {
      return 403;
    }
    internal;
  }

**Comment by ddur** [comment]
I use [WordOps](https://wordops.net/) where Zip & logs are by default protected from download.
