### ISSUE TITLE
Problem path

### ISSUE THREAD

**Issue by expres-web** [YahnisElsts/wp-update-server#26]
Plz, who ist problem? 

Warning: require(/users/zalohovane/44670061/expres-web.cz/www/wp-update-server/plugin-update-checker.php): failed to open stream: No such file or directory in /users/zalohovane/44670061/expres-web.cz/www/wp-content/plugins/wptouch-cestina/wptouch-cestina.php on line 34

Me php info:
http://expres-web.cz/wp-update-server/info.php

Thx

**Comment by jrfnl** [comment]
You're in the wrong repository - you want the [Plugin Update Checker](https://github.com/YahnisElsts/plugin-update-checker).

Also the checker should be installed with the plugin and then the include path would be something like: /users/zalohovane/44670061/expres-web.cz/www/wp-content/plugins/plugins/wptouch-cestina/include/plugin-update-checker/plugin-update-checker.php

Oh and you may want to remove the phpinfo file (security).

**Comment by YahnisElsts** [comment]
I second that.

**Comment by expres-web** [comment]
So the update-checker does not have to be in the wp-update-server but directly in the plugin?

**Comment by YahnisElsts** [comment]
Of course. Presumably, you're going to distribute your plugin to users somehow. Your users are not going to have `wp-update-server` installed on their site. So to be able to use the update checker, you need to include it in your plugin.
