### ISSUE TITLE
Update changing theme folder name

### ISSUE THREAD

**Issue by explorador** [YahnisElsts/wp-update-server#27]
The API has been working great for months but this week it started to change the theme folder name to:
"actiondownloadslugtheme-name" after I do the update theme in wordpress and it should be "theme-name".

**Comment by fuchsws** [comment]
I'm having the same issue - what could cause this?

**Comment by YahnisElsts** [comment]
I'm not sure. If you download the update manually, does the .zip archive contain the correct folder? 

Also, is you directory structure correct? It should be like this:

```
theme-name.zip
    theme-name/
        style.css
        other-files-here
```

On the other hand, structure like this will *not* work correctly:

```
theme-name.zip
    style.css
    other-files-here
```

In other words, theme files must be in a folder and not at the top of the ZIP file.

**Comment by fuchsws** [comment]
alright sorry, I fixed it: the folder structure was correct, but it contained a "theme-name.zip/.gitignore" file which was causing this. so the "theme-name.zip" may only contain one theme subfolder and no additional files at root level.

**Comment by YahnisElsts** [comment]
Yes, that's right. One folder and nothing else.
