### ISSUE TITLE
Updates working but "progress" gear busy "ad infinitum"

### ISSUE THREAD

**Issue by caraffa** [YahnisElsts/wp-update-server#28]
Good day Yahnis.
First of all thanks for the outstanding job. I've followed your instructions and I'm able to download and install my plugin's updates from the wp-update-server.
If I fire up the update process from the "update-core" core page (i.e.: http://myexmaplesite.com/wordpress/wp-admin/update-core.php for example), the update process is flawless. Each phase is displayed while in progress (maintenance mode activation, zip file download, decompression, etc.) and, at the end, a message notifies me of the successful update.
On the other hand, if I do the same, but from the "installed plugins" page (i.e.: http://myexamplesite.com/wordpress/wp-admin/plugins.php) the process apparently freezes.
The page displays correctly an "update available" warning, but after clicking the "update now" button the "progress gear" starts revolving, the "please wait" notice is displayed but nothing more happens.
If i try to abandon the page, Wordpress warns me that an update is in progress and if I forcibly leave the page, this could break my plugin.
Well, actually this doesn't happen. Actually the plugin is updated correctly. In fact if you forcibly leave the page and reload the plugin page you can see that the plugin has been updated successfully.
So the problem is, apparently, that Wordpress is awaiting for some form of notification at the end of the process that the update-server doesn't give.
By the way, I'm using wp 4.2.2.
Thank you again for your help

**Comment by YahnisElsts** [comment]
The "update now" button works via AJAX. My guess would be that while WordPress is installing the update there is some unexpected output (e.g. a PHP notice) that then gets included in the AJAX response. As a result, the script that handles the update button fails to parse the response and gets stuck. 

To debug something like that, the first thing I would do is look at the HTTP requests sent by the browser. As you probably already know, most modern browsers include a network monitor of some kind. Examine the request that's sent when you click "update now". Usually it will be a POST request to admin-ajax.php. What does the response look like? Or is there no response and the request just times out?

Normally, the response will be a JSON document similar to this:
```json
{"success":true,"data":{"update":"plugin","plugin":"newsletter\/plugin.php","slug":"newsletter","oldVersion":"Version 3.7.8","newVersion":"Version 3.7.9"}}
```

**Comment by caraffa** [comment]
Hi, Yahnis. Thanks for your answare.
This is the JSON response I get:

```JSON
{"success":true,"data":{"update":"plugin","plugin":"CkTellNotifier/plugin.php","slug":"cktellnotifier","oldVersion":"Versione 0.1","newVersion":"Versione 0.99rc1"}}
```

So, apparently there is nothing wrong. The only thing I'm seeing that looks different is the CapitalCase name of my plugin.

**Comment by caraffa** [comment]
Sorry. I Inadvertently hit the "Close and comment" button instead of the "Comment" one.

**Comment by YahnisElsts** [comment]
That JSON looks correct to me. Is there *anything* else in the response - stray whitespace, perhaps? Are there any error messages in the JS console?

The capital-cased `plugin` field shouldn't matter - as far as I can tell, the script that runs AJAX updates (`/wp-admin/js/updates.js`) doesn't actually use it. The `slug` is the important bit. WP uses that to find the right plugin table row and replace the "updating" message with "updated!".

Anyway, the next thing I would try is sprinkling some `console.log()`'s into the `wp.updates.updateSuccess` method in `updates.js` to see if it actually receives the response and where things go wrong.

**Comment by caraffa** [comment]
Well, I've used Firefox and Safari to monitor network traffic and both don't have a "raw" view for the JSON response. Both display a neat list of key/values, so that i cannot say if there is something wrong in the actual JSON formatting. But my guess is that if the browser is displaying the answer in such a neat way, than it is highly improbable that some form of spurious chars are in the way.
That said, I'll follow your advice, and will try the console.debug approach to see what happens.
I'll let you know. Thanks

**Comment by YahnisElsts** [comment]
> Well, I've used Firefox and Safari to monitor network traffic and both don't have a "raw" view for the > JSON response.

Yes, I've noticed that, too. I think Chrome has an option to display the raw response. But you're probably right - if the browser can parse the JSON, WordPress shouldn't have any problems with it either.

**Comment by caraffa** [comment]
Caught!
The problem, as suspected, was the "CamelCase" in my plugin name. For really mysterious reasons the wp_ajax_update_plugin function in the ajax-actions.ph file "sanitizes" the slug, which, among others, lowerize it (why do that in the plugins.php page and NOT in the update-core-php page? Who knows!!!!)
I've replaced the ``` 'slug' => sanitize_key( $_POST['slug'] ), ``` with a much more reasonable ``` 'slug' => preg_replace( '/[^A-Za-z0-9_\-]/', '', $_POST['slug'] ), ``` and everything is working fine.
So the culprit was Wordpress and your code is as innocent as a newborn baby ;-).
Thank you again for your valuable help.

**Comment by YahnisElsts** [comment]
Side note: Chances are that WP core developers didn't notice that issue because all plugins on wordpress.org have lowercase directory names. WordPress is not designed to support installing updates from third-party sources, so this particular scenario probably never got tested.

**Comment by caraffa** [comment]
Yes. In fact I've submitted a bug report, explaining the whole issue, along with a fix proposal.

**Comment by jrfnl** [comment]
@caraffa I'd like to follow the bug report - could you post a link to it here ?

**Comment by jrfnl** [comment]
Never mind - found it: https://core.trac.wordpress.org/ticket/32465
