### ISSUE TITLE
Cannot modify header information

### ISSUE THREAD

**Issue by Xyolyp** [YahnisElsts/wp-update-server#31]
When I try to open http://www.domain.com/index.php (where my WP is installed) I just get:
Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/w00ea973/wordpress/wp-content/plugins/myPlugin/myPlugin.php:1) in /www/htdocs/w00ea973/wordpress/wp-includes/pluggable.php on line 1207
What can I do against that? I just copy-pasted your Code to my plugin, the updating procedure works flawlessly but whenever I try to open a *.php file I just get that error. 
I would like to use your code but I can't when it breaks almost the entire backend.

**Comment by YahnisElsts** [comment]
Take a look at your PHP error log. There's probably some kind of a notice or warning that's showing up on the page and forcing PHP to send headers earlier than necessary.

**Comment by Xyolyp** [comment]
Thank you for the fast answer! 
I just checked the errorlog and all that is in there is
[29-Sep-2015 12:40:54 UTC] PHP Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/w00ea973/wordpress/wp-content/plugins/myPlugin/myPlugin.php:1) in /www/htdocs/w00ea973/wordpress/wp-includes/pluggable.php on line 1207
Do you have another idea what I can do to prevent that?
On activation of the plugin Wordpress prints a notice in german (I'm german) which translates to:
The plugin caused an error message 3 characters of unexpected output during the activation. If you get errors like "headers already sent" roblems with the syndication of the feeds or other errors, try to disable or delete the plugin.
I think the outputs are for debugging purposes and I ignored the warning because I think that are just "echo"s or something like that. Hopefully you have an idea what I can do.

**Comment by YahnisElsts** [comment]
Could you paste the very top of your myPlugin.php here? Just the first 5 lines or so, including any empty lines and spaces. Based on the error message, there's something wrong with the first line.

Since it's 3 characters, maybe there's a [UTF-8 byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8) at the start of your file. If so, you need to get rid of that.

**Comment by Xyolyp** [comment]
No problem, the end of the comment will be the first ~30 lines of the plugin 'cause I don't think there is something wrong in line 1 because if I remove the code between the comments then I don't get any error.

<?php
/*
* Plugin Name: my Plugin
* Description: My first Plugin
* Version: 1.0.1
* Author: Me
* Author URI: http://www.domain.com
*/

defined( 'ABSPATH' ) or die( 'Forbidden.' );


//////////////////////////////////////
/////////// AUTO UPDATE //////////////
//////////////////////////////////////
$plugin_basename = plugin_basename( __FILE__ );
$plugin_slug_array = explode("/", $plugin_basename);
require 'plugin-update-checker/plugin-update-checker.php';
$MyUpdateChecker = PucFactory::buildUpdateChecker(
'http://my.domain.eu/?action=get_metadata&slug=' . $plugin_slug_array[0], //Metadata URL.
__FILE__, //Full path to the main plugin file.
$plugin_slug_array[0] //Plugin slug. Usually it's the same as the name of the directory.
);
//////////////////////////////////////
///////// END AUTO UPDATE ////////////
//////////////////////////////////////

**Comment by YahnisElsts** [comment]
I don't see anything immediately wrong with the code, though the formatting is a bit messed up (see [GitHub docs](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) for how to format code samples).

Try running your plugin PHP file and the `plugin-update-checker.php` file through the [BOM Detector](http://www.bryntsoft.com/filebomdetector.htm) app. If it finds anything, righ-click on the file in the app and click "Remove BOM".

**Comment by Xyolyp** [comment]
Great advise! It found an error in the thumbs.db, fixed it and now everything works just as wanted. 
Thanks for your help!
