### ISSUE TITLE
Possible update needed because of changes in core

### ISSUE THREAD

**Issue by jrfnl** [YahnisElsts/wp-update-server#34]
See https://core.trac.wordpress.org/ticket/35301

**Comment by YahnisElsts** [comment]
Thank you. Noted. This should be pretty easy to deal with on the server side.

**Comment by YahnisElsts** [comment]
This was fixed a while ago in YahnisElsts/plugin-update-checker@67fb7c0e6b5a21e0d42f37e32d6e330607fc8777, but I forgot to close the issue. Closing it now.
