### ISSUE TITLE
Question about sending data during an "update" check

### ISSUE THREAD

**Issue by misulicus** [YahnisElsts/wp-update-server#36]
Got a weird question maybe. Either using the update server or with the plugin updater code. (would prefer from within the server updater for old plugin users)

For example when a plugin automatically checks for updates and its passing along a license key. Would it be possible to send a "message" back that gets displayed to the user like an admin notice ?

For example on an update check and the users license is expired to send them back a message to let them know its expired and that they need to renew ?

**Comment by YahnisElsts** [comment]
There's no *built-in* way to do that, but it shouldn't be too hard to implement it by extending the server and update checker. I've done it for one of my plugins. 

The basic idea is this: on the server, override the `filterMetadata` method and include your message in the update metadata. In your plugin, use the `puc_request_info_result-$slug` filter to extract the message and save it somewhere. Then display it as an admin notice.

**Comment by arunbasillal** [comment]
Hello @misulicus 

I am not sure if you implemented this, I just did for one of my plugins. Thanks to the outline from the author.

- In the update server I overrode `filterMetadata` and added license validation based on the general idea here: http://w-shadow.com/blog/2013/03/19/plugin-updates-securing-download-links
- Along with `unset($meta['download_url']);` I added a `$meta['upgrade_notice']`
- On the WordPress plugin end, I used the `requestInfo()` function to get all the meta data as an object. 
- Using the action hook `in_plugin_update_message-{$file}` I added a notice in the plugins page - https://developer.wordpress.org/reference/hooks/in_plugin_update_message-file/ 
- For the notice part, you can find more info here: https://wordpress.stackexchange.com/a/33529/90061

Hope that helps someone in their journey. Thanks @YahnisElsts for all your hard work!

**Comment by YahnisElsts** [comment]
That sounds like a pretty good solution. The only thing that I would add is that it would probably be a good idea to cache the `requestInfo()` return value somewhere because you probably don't want to slow down the site by making a new HTTP request every time someone opens the "Plugins" page.

The original post is quite old now, so I'm going to close this issue. If you have any further comments, feel free to re-open.

**Comment by arunbasillal** [comment]
Thanks for the validation @YahnisElsts, caching / saving `requestInfo()` sounds like a plan, I will add that :)
