### ISSUE TITLE
preg_replace notifications oh PHP 7

### ISSUE THREAD

**Issue by misulicus** [YahnisElsts/wp-update-server#38]
`PHP Warning:  preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead`

when used as a WordPress plugin.

**Comment by YahnisElsts** [comment]
Is there a file name and line number to go with that warning? I did a quick scan of the source code but didn't find any usages of the `/e` flag. (Maybe it's in a third-party library.)

**Comment by YahnisElsts** [comment]
Any news on this? If not, I'm going to close this as not reproducible.

**Comment by misulicus** [comment]
Can be closed for now
