### ISSUE TITLE
Not showing update.

### ISSUE THREAD

**Issue by ShamarKellman** [YahnisElsts/wp-update-server#39]
I have followed the instructions. When i go the the meta-data URL, I can see the meta data. The request logs show the request to the server. However WordPress doesn't show there is an update.  The theme installed version 1.1, the update is 1.2. Can you please help with this.
Thank you

**Comment by YahnisElsts** [comment]
Here are a few things to check:

- Verify that the correct theme slug is passed to the ThemeUpdateChecker constructor. Usually it should match the theme directory name.
- Verify that you have the latest version of the update checker (1.2).
- Try running `$updateChecker->requestUpdate()` and `var_dump()` the result. Does it return a `ThemeUpate` instance and does it have the expected version number?
- Take a look at the `external_theme_updates-$themeSlug` option in the `wp_options` table. It should contain a serialized PHP object. Is it present and does it have the right version number?

**Comment by ShamarKellman** [comment]
Thanks for the quick response. I found the issue, there was bad data in the `_site_transient_update_themes` option field in the database which was preventing the theme from showing the update. 

It works! 
Thanks

**Comment by YahnisElsts** [comment]
All right, good to know.
