### ISSUE TITLE
Changing theme directory name

### ISSUE THREAD

**Issue by DannyCooper** [YahnisElsts/wp-update-server#43]
I'm using the updater script within a theme, however when the updater runs it's adding six characters to the end of the directory name, for example:

ot-cadmus becomes ot-cadmus-TBZOiN

Do you have any idea what could be causing that?

Thanks in advance for any guidance.

**Comment by YahnisElsts** [comment]
That can happen when the update ZIP file is not structured correctly. Verify that all theme files are inside a directory, not at the root of the ZIP file. 

Be especially careful with this if you're using OS X. According to multiple user reports, the default ZIP app on that OS can make it look like the files are in a directory when they're actually not. Use a third-party archiver instead.

**Comment by DannyCooper** [comment]
Thank you Yahnis, that was the exact problem. The files were in the root of the .zip using OSX.

This is a really useful package, thanks for releasing it!
