### ISSUE TITLE
Split logs per month / days

### ISSUE THREAD

**Issue by max-kk** [YahnisElsts/wp-update-server#46]
Hi Yahnis,

Forst - thanks for the great software ☺.

Second - how do you think about splitting Log to separate files based on a month or a day for make them more readable?

Regards, Max

**Comment by YahnisElsts** [comment]
Some kind of log rotation or splitting would certainly be useful, but I'm not sure if it should be part of this software when there are already existing tools that can do it for you, e.g. [logrotate](http://www.linuxcommand.org/man_pages/logrotate8.html). Also, the server doesn't have any kind of daemon/supervisor/long-lived process, so it would be tricky to implement file manipulation without running into concurrency-related problems.

**Comment by YahnisElsts** [comment]
I've added some very basic, limited log rotation support. To enable it, call `Wpup_UpdateServer::enableLogRotation`. Example:

```php
$server->enableLogRotation(
    Wpup_UpdateServer::FILE_PER_MONTH, //Monthly rotation.
    6 //Keep the last 6 files.
)
```

I would still recommend using the logrotate tool for anything more complex.
