### ISSUE TITLE
Idea: better support for plugin banners

### ISSUE THREAD

**Issue by d4b** [YahnisElsts/wp-update-server#47]
Example UpdateServer.php

	protected function filterMetadata($meta, $request) {
		//By convention, un-set properties are omitted.
		$meta = array_filter($meta, function ($value) {
			return $value !== null;
		});
		
		$low_banner = 'http://' . $plugin_url . 'banners/' . $slug .'-772-250.png';
		$high_banner = 'http://'. $plugin_url . 'banners/' . $slug .'-1544-500.png';
		$banner_array = array('low' => $low_banner,'high' => $high_banner);
		$meta['banners'] = $banner_array;
		
		return $meta;
	}

**Comment by mattiasghodsian** [comment]
I agree there should be a better way to add banner meta, i posted a similar code on Yahnis blog a while ago.

http://w-shadow.com/blog/2013/03/19/plugin-updates-securing-download-links/#comment-711002

**Comment by YahnisElsts** [comment]
All right, I've added something like that. Give it a shot.

Name the banners `slug-772x250.png` (or `.jpg`) and `slug-1544x500.png`, and put them in the `banners` sub-directory.
