### ISSUE TITLE
license integration

### ISSUE THREAD

**Issue by d4b** [YahnisElsts/wp-update-server#48]
Hello
What you are using to handle the license?
I think about the integration of https://pl.wordpress.org/plugins/software-license-manager/

**Comment by mattiasghodsian** [comment]
Im using a "home made" license system

**Comment by d4b** [comment]
So there is no built-in / native and you have to use something else?

**Comment by mattiasghodsian** [comment]
You are freely to use anything, remember you need to code the connection yourself on the wp-update-server to the plugin or code you decide to use.

**Comment by YahnisElsts** [comment]
There is no built-in support for license management. I'm also using my own, home-grown system. 

You might find this post useful:
http://w-shadow.com/blog/2013/03/19/plugin-updates-securing-download-links/

**Comment by d4b** [comment]
What do you recommend for complex service?

**Comment by mattiasghodsian** [comment]
Depends on what u need.

**Comment by YahnisElsts** [comment]
It's likely that you would need to write your own integration.
