### ISSUE TITLE
Can't use update server as a plugin on a wordpress installation

### ISSUE THREAD

**Issue by shivanandwp** [YahnisElsts/wp-update-server#50]
includes/WPup/UpdateServer.php:line 148
function validateRequest throws `You must specify an action.`

This is not practical when the update server is installed as a WordPress Plugin since it throws:

400 Bad Request
You must specify an action.

When a visitor is visiting the homepage then the plugin shouldn't check for action. Instead should just let WordPress do its thing and serve the homepage instead of json.

**Comment by shivanandwp** [comment]
A check is in order:

===
if ( get_query_var('action') ) {
$server->handleRequest();
===

**Comment by YahnisElsts** [comment]
When using the server as part of a plugin, you're not supposed to just run it blindly. You need to verify the necessary parameters and pass them to the handleRequest() method. Take a look at the example code in the readme. It does check if the action is specified before calling the server:
https://github.com/YahnisElsts/wp-update-server#running-the-server-from-another-script

**Comment by shivanandwp** [comment]
I think it's best to update the index.php with the same.

**Comment by YahnisElsts** [comment]
I disagree. index.php is the entry point for the stand-alone version of the server. Do you really want it to fail silently if some of the parameters are missing? That would make setup and debugging more difficult.

**Comment by steeevio** [comment]
I'm trying to use the sample code for a wordpress plugin from here https://github.com/YahnisElsts/wp-update-server - but I keep getting an error when checking for updates "Could not determine if updates are available for SJEV Test plugin. Failed to parse update metadata. Try validating your .json file with http://jsonlint.com/ puc-invalid-json"

Any ideas what could be causing this? 

Thanks

**Comment by YahnisElsts** [comment]
Try opening the metadata URL in your browser. What does the page say, if anything?

**Comment by steeevio** [comment]
how would I get the metadata url?

**Comment by YahnisElsts** [comment]
Presumably, you already have it. It's the URL that you pass to the `buildUpdateChecker()` method.

**Comment by steeevio** [comment]
Oh I see, thanks! So it seems that my problem is that none of the wordpress functions are available when I  access it with the url in this way. For example I get "Fatal error: Call to undefined function home_url() in /home/encoremedia/public_html/wp-content/plugins/sjev_plugin-server/sjev_plugin-server.php on line 31"

**Comment by YahnisElsts** [comment]
It sounds like you might be accessing plugin PHP files directly instead of going through WordPress. You *can* do that - I've done it myself as a way to improve performance - but then you have to carefully design your plugin so that it works both inside WP and as a stand-alone script.

Are you sure you're using the right URL? When embedding the server in a plugin, the URL would typically be something like this:
`https://example.com/?your_action_param=get_metadata&your_slug_param=plugin-slug`

On the other hand, this would be incorrect:
`https://example.com/wp-content/plugin-name/plugin-name.php?action=get_metadata&slug=plugin-slug`

**Comment by steeevio** [comment]
That is exactly what I was doing! I had it working as a standalone script before and didn't update the url in the plugin. Thanks very much for your help. Working perfectly now.
