### ISSUE TITLE
Made an Envato Compatible Server

### ISSUE THREAD

**Issue by swashata** [YahnisElsts/wp-update-server#56]
Hello,

First of all thank you very much for this. It has helped me setup an update server for my envato plugins in just one day. I am really grateful to what you have offered. I have also open sourced my work here https://github.com/WPQuark/wpq-wp-update

I have a few favors to ask you:

1. Right now composer package points to an outdated version. The current one has support for banners, which is awesome. So I used the latest commit tag to include in my composer, but would love to have a release.
2. Instead of logging into file, I am logging into database. Any tips on generating graphs from the database? I have seen your stat package and was wondering where do I need to look for the chart queries?

Thank you once again.

**Comment by swashata** [comment]
Also I am not able to pass the itmversion parameter? Is this something I need to do explicitly from the [plugin update checker](https://github.com/YahnisElsts/plugin-update-checker)?

**Comment by YahnisElsts** [comment]
> Right now composer package points to an outdated version. The current one has support for banners, which is awesome. So I used the latest commit tag to include in my composer, but would love to have a release.

All right, I've released version 1.3.

> Any tips on generating graphs from the database? I have seen your stat package and was wondering where do I need to look for the chart queries?

The code that extracts performance metrics from the log is in `src/BasicLogAnalyser.php` and the stuff that turns those metrics into charts is in `src/Report.php`. I guess you could try writing your own subclass of `\Wpup\BasicLogAnalyser` that reads log entries from the database instead of a file. It would probably be simpler than the existing implementation since you wouldn't have to worry about merging multiple log files and parsing text.

> Also I am not able to pass the itmversion parameter? Is this something I need to do explicitly from the plugin update checker?

Is `itmversion` a custom URL parameter that you need to send from the plugin to the update server? You could append it to the metadata URL or use the `puc_request_info_query_args-$slug` filter. Untested example:

```php
$updateChecker->addFilter('request_info_query_args', function($query) {
    $query['itmversion'] = 'example';
    return $query;
});
```

**Comment by swashata** [comment]
Hello,

Thank you for the follow up.

>Is itmversion a custom URL parameter that you need to send from the plugin to the update server? You could append it to the metadata URL or use the puc_request_info_query_args-$slug filter. Untested example:

Sorry for the confusion. What I actually meant was `installed_version` as in [here](https://github.com/YahnisElsts/wp-update-server/blob/master/includes/Wpup/UpdateServer.php#L338)

Do I need to pass the current plugin version from the plugin itself?

Please see the last logs from the screenshot. Those were sent by calling `Puc_v4_Factory` like [this](https://github.com/WPQuark/wpq-wp-update/blob/develop/client/class-plugin-autoupdate.php#L84)..

So do I need to pass something like `wpq_wp_update_plugin_version => PLUGIN_VERSION` and then catch the `$_GET` within wp-update-server by extending [here](https://github.com/WPQuark/wpq-wp-update/blob/develop/includes/server/class-wpq-wp-update-handler.php#L32)

I was thinking that the `Puc_v4_Factory` plugin itself is responsible for sending current plugin version. If so, then perhaps I am missing something while calling the update server. Do I need to pass in another `$_GET` parameter?

> The code that extracts performance metrics from the log is in src/BasicLogAnalyser.php and the stuff that turns those metrics into charts is in src/Report.php. I guess you could try writing your own subclass of \Wpup\BasicLogAnalyser that reads log entries from the database instead of a file. It would probably be simpler than the existing implementation since you wouldn't have to worry about merging multiple log files and parsing text.

Thank you for the heads up. I will look into it and see what I can make.

**Comment by YahnisElsts** [comment]
No, you don't need to explicitly set the `installed_version` parameter. The update checker is supposed to do that [automatically](https://github.com/YahnisElsts/plugin-update-checker/blob/master/Puc/v4p2/UpdateChecker.php#L438). 

Please double-check the plugin file path that you're passing to `buildUpdateChecker` (in this case that's `self::PLUGIN_ABS_FILE`). PUC will try to read the version number from that file.

> Please see the last logs from the screenshot. Those were sent by calling Puc_v4_Factory like this..

Where is this screenshot?

**Comment by swashata** [comment]
Sorry for missing the screenshot. Here it is. 

![wp-update-log](https://user-images.githubusercontent.com/1623381/29995334-7c6fb5ea-9004-11e7-826e-15c6992fc9be.jpg)


I think I need to catch the `installed_version` parameter.

**Comment by swashata** [comment]
Alright, finally got it working by explicitly passing the `installed_version` and `php` parameters to the update server. https://github.com/WPQuark/wpq-wp-update/blob/develop/includes/server/class-wpq-wp-update-handler.php#L38

**Comment by YahnisElsts** [comment]
Ah, I see. I haven't read the entire source code of your project so I assumed that the update handler would just give `Wpup_UpdateServer` *all* available query parameters (i.e. the entire `$_GET` array), possibly with some modifications like remapped keys. It looks it actually only provides a predefined list. Naturally, in this case the update server won't know about `installed_version` unless you explicitly add it to the the list.

**Comment by swashata** [comment]
Yes that was it. It is resolved now. Bdw, I followed your readme section that talks about integrating with WordPress Plugin. So you may want to update [this](https://github.com/YahnisElsts/wp-update-server/blob/master/README.md#running-the-server-from-another-script) section and document the `$_GET` or manual `query` parameters the server would be expecting.

Thank you for your patience and support.

**Comment by YahnisElsts** [comment]
Noted. For now, I just made a small change to the example code in that section to include `$_GET`.

**Comment by swashata** [comment]
Great. So let's close this issue.
