### ISSUE TITLE
WP Update Server not      work

### ISSUE THREAD

**Issue by adrix71** [YahnisElsts/wp-update-server#58]
Hello, i following all steps describes in this page 

1) The directory wp-update-server is inside of the wp-content directory and renamed in updates.
2) The example plugin is in wp-content/plugins/my-plugins/my-plugins.php
3) The update plugins is zip format (my-plugins.zip) inside wp-content/updates/packages
4) The example plugin is active.

but the test:

`http://my-server.dev/wp-update-server/?action=get_metadata&slug=my-plugins`

or

`http://my-server.dev/updates/?action=get_metadata&slug=my-plugins`

always return  the 404 error page.

Any idea?

**Comment by YahnisElsts** [comment]
Correct if I'm wrong, but if the update server is inside `wp-content/updates`, shouldn't the URL include that directory? 
`http://my-server.dev/wp-content/updates/?action=get_metadata&slug=my-plugins`

**Comment by adrix71** [comment]
You are right. I trusted too much the copy paste. Now it works correctly.
