### ISSUE TITLE
Feature request: support for plugin icons

### ISSUE THREAD

**Issue by robertharm** [YahnisElsts/wp-update-server#59]
Hi @YahnisElsts,

just found that you added "Add the ability to show a plugin icon on the "Dashboard -> Updates" page" to the plugin update checker (https://github.com/YahnisElsts/plugin-update-checker/commit/585f60d91c337667e95e6dbd13f834d9875c9711) - thanks a lot!

I wonder if the wp-update-server could also be enhanced to support this new feature? E.g. by automatically retrieving the needed icons form a new directory `/icons` for example?

If I can help here somehow, let me know!
best,

Robert

**Comment by YahnisElsts** [comment]
Sure, that sounds like a good idea. Try the version that I just committed.

**Comment by robertharm** [comment]
Works great, thanks!

another idea: could translations also be supported?

**Comment by YahnisElsts** [comment]
Translations would be quite a bit more complicated. Why not bundle all translations with the plugin? Download size?

**Comment by robertharm** [comment]
you're right - did not think this true. Currently all translations are already bundled, I just saw that the translation array was empty when using the PUC debug bar addon & thought this could be added too...

**Comment by YahnisElsts** [comment]
It could certainly be added. It's just not as simple as the icon feature. Maybe I'll get around to it some day.

**Comment by robertharm** [comment]
thanks a lot!
