### ISSUE TITLE
Plugin version not working?

### ISSUE THREAD

**Issue by northernbeacheswebsites** [YahnisElsts/wp-update-server#60]
When I installed the server in the root of my website directory it seemed to work fine but when I install it as a plugin it's like the code in the plugin file isn't doing anything.

Below is my full plugin code. I have copied your example plugin exactly, all I have done is changed the MyCustomServer class to include the alternate code you also have in the readme file. And I also changed the require_once URL at the top. 

When I check for updates it shouldn't show the download/update link for the plugin but it is showing it. So it's like the class isn't being fired. What am I doing wrong? 

Thanks for the great work by the way!

```
<?php
/*
Plugin Name: Plugin Update Server
Description: An example plugin that runs the update API.
Version: 1.0
Author: Yahnis Elsts
Author URI: http://w-shadow.com/
*/

require_once __DIR__ . '/wp-update-server/loader.php';

class ExamplePlugin {
	protected $updateServer;

	public function __construct() {
		$this->updateServer = new MyCustomServer(home_url('/'));
		
		//The "action" and "slug" query parameters are often used by the WordPress core
		//or other plugins, so lets use different parameter names to avoid conflict.
		add_filter('query_vars', array($this, 'addQueryVariables'));
		add_action('template_redirect', array($this, 'handleUpdateApiRequest'));
	}
	
	public function addQueryVariables($queryVariables) {
		$queryVariables = array_merge($queryVariables, array(
			'update_action',
			'update_slug',
		));
		return $queryVariables;
	}
	
	public function handleUpdateApiRequest() {
		if ( get_query_var('update_action') ) {
			$this->updateServer->handleRequest(array_merge($_GET, array(
				'action' => get_query_var('update_action'),
				'slug'   => get_query_var('update_slug'),
			)));
		}
	}
}

class MyCustomServer extends Wpup_UpdateServer {
	protected function filterMetadata($meta, $request) {
		$meta = parent::filterMetadata($meta, $request);
		unset($meta['download_url']);
		return $meta;
	}
	
	protected function actionDownload(Wpup_Request $request) {
		$this->exitWithError('Downloads are disabled.', 403);
	}
}

$examplePlugin = new ExamplePlugin();
```

**Comment by YahnisElsts** [comment]
The code looks fine at first glance.

Assuming that this is on a test site and not a production system, let's try to narrow down the problem by a crude process of elimination. Remove or comment out the `MyCustomServer` class. Open the metadata URL in your browser. Does it still work? It shouldn't; the whole thing should crash. If it crashes, restore the class and try throwing an exception in `filterMetadata` to see if the method is being called. On the other hand, if removing the class doesn't seem to do anything, comment out the line that creates an instance of `ExamplePlugin`. Does it stop working now? And so on.

**Comment by northernbeacheswebsites** [comment]
Hi YahnisElsts, this is on a test site which is on a non-local server. Ok, now I am really confused, if I comment out all the code in the plugin file the metadata URL still shows everything! Example:

https://northernbeacheswebsites.com.au/root-nbw/wp-content/plugins/plugin-update-server/wp-update-server/?action=get_metadata&slug=duplicate-post

How could the metadata URL still be working if all the code in the plugin file is commented out? At first I thought it might be a caching issue but I cleared everything. I even commented out the key line:

require_once __DIR__ . '/wp-update-server/loader.php';  

and it still works! This is obviously why my code wasn't doing anything before, but how can this be happening? I have put my sample plugin here if it helps and if you want to test things: https://github.com/northernbeacheswebsites/plugin-update-server

Thanks,

**Comment by YahnisElsts** [comment]
Wait a minute, it looks like you're not actually *using* the plugin. You're accessing the update server directly (`wp-update-server/index.php`) and bypassing WordPress entirely. If you do that, the plugin code will never get a chance to execute.

Instead, use this URL:
https://northernbeacheswebsites.com.au/?update_action=get_metadata&update_slug=duplicate-post

I would also recommend blocking direct access to `.php` files in `wp-update-server`. It looks like you might have done that already since I get an error when I click the example link in your comment.

**Comment by northernbeacheswebsites** [comment]
Ahh, you are the best, thank you! Everything works as expected now. Really appreciate your support and the writing of this plugin.
