### ISSUE TITLE
Playing friendly with WordPress.org updates

### ISSUE THREAD

**Issue by northernbeacheswebsites** [YahnisElsts/wp-update-server#62]
Hi, sorry to bother you again!

I have an unusual use case perhaps but I am not sure how to go about it. I have a plugin which has a free version and a pro version. The free version gets updates from the standard wordpress.org update system, but I want the pro version to use the wp-update-server instead. 

However the pro version is an extension of the free version (so it contains all the same features as the free version and adds some more), and because of this the plugins have the same slug. 

So when the pro version of the plugin is trying to get updates it seems to be using the wordpress.org system and this is over-riding wp-update-server. 

I know I can use code like:

```
add_filter( 'http_request_args', function ( $response, $url ) {
	if ( 0 === strpos( $url, 'https://api.wordpress.org/plugins/update-check' ) ) {
		$basename = plugin_basename( __FILE__ );
		$plugins  = json_decode( $response['body']['plugins'] );
		unset( $plugins->plugins->$basename );
		unset( $plugins->active[ array_search( $basename, $plugins->active ) ] );
		$response['body']['plugins'] = json_encode( $plugins );
	}
	return $response;
}, 10, 2 );
```

to disable updates completely for the plugin but this will disable updates for wp-update-server as well. Is there a solution to this? Thanks,

**Comment by YahnisElsts** [comment]
In general, I would recommend using a different slug for the Pro version. However, even if you use the same slug, PUC updates should still override and replace updates from wordpress.org. So, there are two things to check:

- Is your plugin active? Obviously, you can't get updates from wp-update-server if the code that's responsible for receiving those updates isn't running.
- If it's a Multisite installation, is the plugin active on the main site? Only plugins that are active on the main site will be loaded in the network admin, which means those are the only plugins that can influence which updates are installed.

**Comment by northernbeacheswebsites** [comment]
Hi,

I can confirm the plugin is active. I will look into this further and report back if I can find a solution.

**Comment by northernbeacheswebsites** [comment]
Ahh it turns out it's important that the plugin update checker code is in the main file of the plugin. After I moved my code there things worked as expected. Thanks

**Comment by YahnisElsts** [comment]
The code **doesn't** need to be in the main file of the plugin. You only need to pass the full path to the main plugin file as the second argument to the `buildUpdateChecker()` method.

**Comment by northernbeacheswebsites** [comment]
Thanks, that’s good to know.
 <>                                        	
Martin Gibson  | Designer
Northern Beaches Websites

Collaroy, NSW, 2097 <https://www.google.com.au/maps/place/Collaroy+NSW/@-33.7353528,151.2862191,14z/data=!3m1!4b1!4m5!3m4!1s0x6b0d5542782277f1:0x5017d681632b250!8m2!3d-33.7319791!4d151.3005601>
mobile: 0400 491 712 <tel:+61400491712>  

website <https://northernbeacheswebsites.com.au/> | email <mailto:info@northernbeacheswebsites.com.au>
