### ISSUE TITLE
Not detecting updates

### ISSUE THREAD

**Issue by mcpacific** [YahnisElsts/wp-update-server#73]
I have installed wp-update-server as well as plugin-update-checker. Everything seems to be working without any errors. However, when I click on the 'Check for updates' link under Dashboard > Installed Plugins > My Plugin it says it's up to date, even though the version number installed is 1.0.4 (the latest version of my plugin is 1.0.5, which is correctly shown in the JSON file).

I should also note that the log correctly posts each request from the WordPress installation.

**Comment by YahnisElsts** [comment]
There's a number of things that could cause that. To help narrow it down, please install [Debug Bar](https://wordpress.org/plugins/debug-bar/) and take a look at the "PUC (your-plugin-slug)" section. Do all of the settings shown there look correct? Click the "Check Now" button - does it show the correct update details?

If everything seems to be fine there, it could be a configuration issue of some kind. Please double-check the filename that you're passing to the `buildUpdateChecker`.

**Comment by mcpacific** [comment]
It says, "Failed to retrieve plugin info from the metadata URL." However, I can view the update JSON file directly when I put the URL in a web browser. Upon close inspection I see the checker is prefeixing the slug of my plugin with 'plugin-', so the URL is not correct.
