### ISSUE TITLE
Scheduled event, puc_cron_check_updates-plugin-slug, failed to run

### ISSUE THREAD

**Issue by janeks** [YahnisElsts/wp-update-server#74]
Error in WP Site Health:  The scheduled event, puc_cron_check_updates-plugin-slug, failed to run.

Plugin Update Checker Library 4.6. A few plugins with the same library but no other error messages.

**Comment by YahnisElsts** [comment]
There are a few different things that could cause something like that.

How much traffic does the site get? By default, WordPress Cron is only triggered on a pageload, so if there's not a lot of visitors then some scheduled events could be missed. 

I'm not deeply familiar with how this Cron implementation works, but I think a fatal error in a cron job could also prevent it from running some jobs/events. Are there any recent errors in the PHP error log? The error (if any) might not mention this library or the plugin that uses it. An error in another plugin's cron job could be the cause.

**Comment by janeks** [comment]
Did happen on the client's site I have no access to.  I'm going to include it in our documentation. 
Thank you.
