### ISSUE TITLE
"Requires PHP" not shown in JSON output

### ISSUE THREAD

**Issue by galbaras** [YahnisElsts/wp-update-server#76]
My readme.txt file contains the line "Requires PHP: 5.6", but there is no "requires_php" field in the JSON array. In fact, I don't see any code for handling this (new?) field.

Please add this field, because WordPress makes use of it, if it's there.

**Comment by YahnisElsts** [comment]
I have added this field. It will show up as `requires_php` in JSON metadata.

Note that if you want to test this new feature with an existing server installation, you might need to clear the cache first by deleting the `metadata*` files in the `cache` directory.
