### ISSUE TITLE
Syntax with curly braces is deprecated - PHP 7.4

### ISSUE THREAD

**Issue by janeks** [YahnisElsts/wp-update-server#79]
Just FYI: 
Array and string offset access syntax with curly braces is deprecated in ...\update-server\includes\extension-meta\markdown.php on line 949 plus around 20 similar messages.

**Comment by YahnisElsts** [comment]
I've just committed a patch that should fix these deprecation messages. Please give it a try.

**Comment by janeks** [comment]
Thank you.
