### ISSUE TITLE
How to support plugin and theme updates with same slug?

### ISSUE THREAD

**Issue by marcorocca** [YahnisElsts/wp-update-server#80]
Hello, I have a subtle problem: my project has a theme and a main plugin with same slug.

On the update server I must upload in the packages folder a zip file having the same name as the directory containing the plugin and the theme generating a conflict situation.

WordPress supports this because plugins and themes don't share the same folder. How can I do the same thing with wp-update-server?

At the moment I think the only way is to rename one of the slugs with a different name.

**Comment by YahnisElsts** [comment]
I think that in the current implementation it's just not possible to have two different things with the same slug. The update server was designed with the assumption that every package will have a unique slug.

**Comment by marcorocca** [comment]
Ok, thank you, I will rename one of the two with a different slug.
