### ISSUE TITLE
عدم نمایش اطلاعات افزونه

### ISSUE THREAD

**Issue by afagh11943** [YahnisElsts/wp-update-server#88]
به چه صورت باید وقتی کاربر روی لینک مشاهده جزئیات در قسمت افزونه ها کلیک مینماید جزئیات افزونه را به آن نشان دهیم

**Comment by afagh11943** [comment]
``https://s17.picofile.com/file/8414414050/all1.jpg

**Comment by afagh11943** [comment]
همانطور که در تصویر بالا مشاهده میکنید هیچ اطلاعاتی از افزونه نمایش داده نمی شود
اگر ممکن است یک فایل نمونه از نمایش اطلاعات افزونه در اختیار من قرار دهید
و محل قرار گیری فایل نمایش اطلاعات افزونه را اعلام نمایید

**Comment by afagh11943** [comment]
لطفا دررابطه با این موضوع به من کمک کنید

**Comment by YahnisElsts** [comment]
PUC includes a sample file: [/examples/plugin.json](https://github.com/YahnisElsts/plugin-update-checker/blob/4bd0a820d1ed1f8713be141ad56cf5362f83a524/examples/plugin.json)

If you're using `wp-update-server`, you don't need to write that JSON yourself - the server will generate it for you based on the contents of the `readme.txt` file. Make sure that your plugin has a readme and that it is formatted according to WordPress.org standards:
[https://wordpress.org/plugins/readme.txt](https://wordpress.org/plugins/readme.txt)

You can validate the file with the [Readme Validator](https://wordpress.org/plugins/developers/readme-validator/).

**Comment by afagh11943** [comment]
من چگونه می توانم مواردی را که داخل فایلPlugin. Jsاست را داخل فایلReadme. txt قرار دهم. 
لطفا اگر امکان دارد به عنوان نمونه شما موارد فایلplugin. Jsرا داخل یک فایلreadme. Txtقرار دهید و آن فایل را جهت دانلود برای من قرار دهید. 
و در مرحله بعد فایل readme. Txtرا کجای سرور باید اپلود نمایم.

**Comment by afagh11943** [comment]
مشکل که در بالا مطرح کردم حل شد
سوال دیگر این است :
چگونه موارد زیر را در فایل
reademe.txt
پیاده سازی نمایم

"rating": 90,
	"num_ratings": 123,

	"downloaded": 1234,
	"active_installs": 12345

**Comment by YahnisElsts** [comment]
Unfortunately, this update server doesn't have the ability to output ratings and download/install statistics. If you want to do that, you would have to either generate the JSON yourself, or change the update server source code and make it include that information.

**Comment by afagh11943** [comment]
در فایل 
readme.txt
جهت نمایش تصاویر ادرس تصاویر را به شکل زیر وارد نمودم ولی به جای نمایش تصاویر لینک آنها را نشان میدهد
== Screenshots ==

1. http://dl.dehkadeh-cms.ir/wp-update-server/package-assets/banners/banner-772x250.png
2. http://dl.dehkadeh-cms.ir/wp-update-server/package-assets/banners/banner-1544x500.png
![tasvir](https://user-images.githubusercontent.com/49753686/99542026-ce84b880-29c6-11eb-8055-0915e301789e.jpg)

**Comment by afagh11943** [comment]
مشکل را پیدا کردم متشکر هستم باید به شکل زیر کد را قرار دهیم
== Screenshots ==
<img src="http://dl.dehkadeh-cms.ir/wp-update-server/package-assets/banners/screenshot-1.png" alt="Girl in a jacket" width="500" height="600">
<img src="http://dl.dehkadeh-cms.ir/wp-update-server/package-assets/banners/screenshot-2.png" alt="Girl in a jacket" width="500" height="600">
