### ISSUE TITLE
where I have to put example-theme.zip and which class is correct ?

### ISSUE THREAD

**Issue by Alireza-Ghavabesh** [YahnisElsts/wp-update-server#97]
1. my question is, where I have to put example-theme.zip ? in the packages directory?
I also like to say that when I place example-theme.zip in packages directory in wp-update-server and check this url :
(http://localhost/wp-update-server/?action=get_metadata&slug=example-theme) in the browser,
I receive this response json in browser:
**{
"name": "example-theme",
"version": "1.8",
"homepage": "http://localhost/example-theme/",
"author": "the WordPress team",
"author_homepage": "http://localhost/",
"details_url": "http://localhost/my-theme-changelog/my-theme-changelog.html",
"last_updated": "2021-05-21 11:24:06",
"slug": "example-theme",
"download_url": "http://localhost/wp-update-server/?action=download&slug=example-theme",
"request_time_elapsed": "0.018"
}**
2. which class is correct ? (**Puc_v4_Factory::buildUpdateChecker**  or   **ThemeUpdateChecker**) for functions.php in my example-theme

thankyou alot

**Comment by YahnisElsts** [comment]
1. Yes, put the ZIP file in the `packages` directory. If you're getting a valid JSON response, the ZIP file is probably already in the right place.
2. `Puc_v4_Factory::buildUpdateChecker()` is the more recent version. `ThemeUpdateChecker` is outdated and no longer maintained. It might still work, but I would not recommend using it in new projects.

**Comment by Alireza-Ghavabesh** [comment]
currently my example-theme have a Enable auto-update & Disable auto-update Button but although my theme version is:
2.0
and new updated theme in server (in packages folder) is 2.1 but there is no yellow notification for updating theme !

can you tell me what is my mistake ?!
![Uploading Screenshot (45).png…]()

**Comment by YahnisElsts** [comment]
Your screenshot isn't showing up for some reason. However, based on the JSON that you posted earlier, the version on the server is 1.8, not 2.1. Are you sure you have the latest version in the `packages` directory? It might still have an older file, or the version number in the file is incorrect.

**Comment by Alireza-Ghavabesh** [comment]
![Screenshot (46)](https://user-images.githubusercontent.com/58913940/119226352-dcee9100-bb1d-11eb-87a9-7f6b4e7327e4.png)

{
"name": "example-theme",
"version": "2.1",
"homepage": "http://localhost/example-theme/",
"author": "the WordPress team",
"author_homepage": "http://localhost/",
"details_url": "http://localhost/my-theme-changelog/my-theme-changelog.html",
"last_updated": "2021-05-22 10:33:13",
"slug": "example-theme",
"download_url": "http://localhost/wp-update-server/?action=download&slug=example-theme",
"request_time_elapsed": "0.005"
}
============================================> on in the packages

style.css in themes/example-theme directory:
/*
Theme Name: example-theme
Text Domain: example-theme
Version: 2.0
Requires at least: 4.7
Requires PHP: 5.2.4
Description: Our example-theme is designed to take full advantage of the flexibility of the block editor. Organizations and businesses have the ability to create dynamic landing pages with endless layouts using the group and column blocks. The centered content column and fine-tuned typography also makes it perfect for traditional blogs. Complete editor styles give you a good idea of what your content will look like, even before you publish. You can give your site a personal touch by changing the background colors and the accent color in the Customizer. The colors of all elements on your site are automatically calculated based on the colors you pick, ensuring a high, accessible color contrast for your visitors.
Tags: blog, one-column, custom-background, custom-colors, custom-logo, custom-menu, editor-style, featured-images, footer-widgets, full-width-template, rtl-language-support, sticky-post, theme-options, threaded-comments, translation-ready, block-patterns, block-styles, wide-blocks, accessibility-ready
Author: the WordPress team
Author URI: http://localhost/
Theme URI: http://localhost/example-theme/
License: GNU General Public License v2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
Details URI: http://localhost/my-theme-changelog/my-theme-changelog.html

All files, unless otherwise stated, are released under the GNU General Public
License version 2.0 (http://www.gnu.org/licenses/gpl-2.0.html)

This theme, like WordPress, is licensed under the GPL.
Use it to make something cool, have fun, and share what you've learned
with others.

I'm very surprised, everything looks ok ...!

**Comment by YahnisElsts** [comment]
That looks OK to me, too. The version numbers are correct, and the fact that the JSON response shows the new version means that the ZIP file is in the right place.

Could it be that the code that sets up the update checker is wrong? Please make sure that it has the right URL, file name and theme slug.

**Comment by Alireza-Ghavabesh** [comment]
![Screenshot (48)](https://user-images.githubusercontent.com/58913940/119227263-3bb60980-bb22-11eb-8b82-2b42b5effcc1.png)

**Comment by YahnisElsts** [comment]
I *think* that looks fine. And this theme is active, yes? 

If it still doesn't work, try installing the [Debug Bar](https://wordpress.org/plugins/debug-bar/) plugin and look at he "PUC (example-theme)" panel in the debug bar. Does it show the correct information for your theme? You can also try manually triggering an update check (there should be a button for that in the panel) and see what happens.

**Comment by Alireza-Ghavabesh** [comment]
tnx tnx ! 

all of my problem fixed and it worked very well !

just i have some questions:

1. i want to set an icon for my notification.
![781ec2f1-0f9d-41bd-8bdb-570d5fecc5ea](https://user-images.githubusercontent.com/58913940/119232086-1f719700-bb39-11eb-9701-09e086907754.jpg)
like that in the screenshot
I will be grateful if you can give me a link contain some guide about **customizing and prettify yellow notification**.

thanck you very much

**Comment by YahnisElsts** [comment]
That looks like a custom icon that was probably added by another plugin or theme. I don't know how it was done. This update checker doesn't have a feature like that. It just lets WordPress core generate the notifications.
